[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"
  publish = "build/client"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

[dev]
  command = "pnpm run dev"
  port = 5173
  publish = "build/client"
